// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace TargetTypePrediction
{
    public partial class TargetTypeModel
    {
        /// <summary>
        /// model input class for TargetTypeModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"TargetType")]
            public string TargetType { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Range(m)")]
            public float Range_m_ { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Speed(m/s)")]
            public float Speed_m_s_ { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"RadarCrossSection(sq.m)")]
            public float RadarCrossSection_sq_m_ { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Direction(deg)")]
            public float Direction_deg_ { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Height(deg)")]
            public float Height_deg_ { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"CrossParameter(m)")]
            public float CrossParameter_m_ { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Size(m)")]
            public float Size_m_ { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Altitude(m)")]
            public float Altitude_m_ { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Maneuverability")]
            public float Maneuverability { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"EmissionSignature")]
            public float EmissionSignature { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"TargetIntent")]
            public string TargetIntent { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"FlightPathPredictability")]
            public string FlightPathPredictability { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for TargetTypeModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"TargetType")]
            public uint TargetType { get; set; }

            [ColumnName(@"Range(m)")]
            public float Range_m_ { get; set; }

            [ColumnName(@"Speed(m/s)")]
            public float Speed_m_s_ { get; set; }

            [ColumnName(@"RadarCrossSection(sq.m)")]
            public float RadarCrossSection_sq_m_ { get; set; }

            [ColumnName(@"Direction(deg)")]
            public float Direction_deg_ { get; set; }

            [ColumnName(@"Height(deg)")]
            public float Height_deg_ { get; set; }

            [ColumnName(@"CrossParameter(m)")]
            public float CrossParameter_m_ { get; set; }

            [ColumnName(@"Size(m)")]
            public float Size_m_ { get; set; }

            [ColumnName(@"Altitude(m)")]
            public float Altitude_m_ { get; set; }

            [ColumnName(@"Maneuverability")]
            public float Maneuverability { get; set; }

            [ColumnName(@"EmissionSignature")]
            public float EmissionSignature { get; set; }

            [ColumnName(@"TargetIntent")]
            public float[] TargetIntent { get; set; }

            [ColumnName(@"FlightPathPredictability")]
            public float[] FlightPathPredictability { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("TargetTypeModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("TargetType");
            if (labelColumn == null)
            {
                throw new Exception("TargetType column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
